# Generated by Django 3.2 on 2022-01-07 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterialrecieved',
            old_name='time_of_day',
            new_name='date',
        ),
    ]
