# Generated by Django 3.2 on 2022-01-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0002_rename_time_of_day_rawmaterialrecieved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disribution',
            name='branch',
            field=models.CharField(choices=[('jericho', 'Jericho'), ('ring_road', 'Ring Road'), ('bodija', 'Bodija')], default='Jericho', max_length=255),
        ),
    ]
