# Generated by Django 3.2 on 2022-01-08 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0003_disribution_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endofdayreport',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyReport.disribution'),
        ),
    ]
