# Generated by Django 3.2 on 2022-01-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0004_alter_endofdayreport_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('evening_report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dailyReport.endofdayreport')),
                ('morning_report', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dailyReport.rawmaterialrecieved')),
            ],
        ),
    ]
