# Generated by Django 3.2 on 2022-01-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0005_fullreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('meat_pie', 'Meat Pie'), ('chicken_pie', 'Chicken Pie'), ('doughnut', 'Doughnut')], max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialrecieved',
            unique_together={('material', 'date')},
        ),
        migrations.AddConstraint(
            model_name='rawmaterialrecieved',
            constraint=models.UniqueConstraint(fields=('material', 'date'), name='material for a day'),
        ),
        migrations.AddField(
            model_name='pastry',
            name='raw_materials',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailyReport.rawmaterialrecieved'),
        ),
    ]
