# Generated by Django 3.2 on 2022-01-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0006_auto_20220109_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastry',
            name='raw_materials',
        ),
        migrations.RemoveConstraint(
            model_name='rawmaterialrecieved',
            name='material for a day',
        ),
        migrations.AlterUniqueTogether(
            name='rawmaterialrecieved',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Pastry',
        ),
    ]
