# Generated by Django 3.2 on 2022-01-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0007_auto_20220109_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('meat_pie', 'Meat Pie'), ('chicken_pie', 'Chicken Pie'), ('doughnut', 'Doughnut')], max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Pastries',
        ),
        migrations.AddField(
            model_name='rawmaterialrecieved',
            name='pastry',
            field=models.CharField(choices=[('meat_pie', 'Meat Pie'), ('chicken_pie', 'Chicken Pie'), ('doughnut', 'Doughnut')], default='meat_pie', max_length=50),
            preserve_default=False,
        ),
    ]
