# Generated by Django 3.2 on 2022-01-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0008_auto_20220109_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastry',
            name='amount',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
