# Generated by Django 3.2 on 2022-01-11 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dailyReport', '0009_pastry_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='disribution',
            name='pastries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dailyReport.pastry'),
        ),
    ]
