name: FoodCo App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  foodco-build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        
    - name: Build Notifications
      uses: act10ns/slack@v1.5.0
      with:
        config: .github/slack.yaml
        status: ${{ job.status }}
        steps: ${{ toJson(steps) }}
        channel: '#foodco-backend-build'
      if: always()
